"type:docs":
- changed-files:
  - any-glob-to-any-file: docs/**
"type:test":
- changed-files:
  - any-glob-to-any-file: tests/**
"type:ci":
- changed-files:
  - any-glob-to-any-file: .github/workflows/**
"type:feature":
- head-branch: ['^feature', 'feature']
