name: Build BlazeBuild

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        working-directory: blazebuild

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.4.0"

      - name: Install Dependencies
        run: npm install -D

      - name: Build with TypeScript
        run: npx tsc
